version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8015:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./customs:/mnt/extra-addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    command: >
      odoo -c /etc/odoo/odoo.conf 
  mydb:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5060:80"
volumes:
  odoo-web-data:
  odoo-db-data:
